name: Maven Test With Foresight CLI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.thundra.me
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          mvn clean install 
      - name: Thundra Registry
        if: success() || failure()
        run: |
          npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
          npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
          ls -lR
      - name: Foresight Action
        if: success() || failure()
        uses: thundra-io/foresight-test-kit-action@master
        with:
          api_key: ${{ secrets.THUNDRA_APIKEY }}
          test_framework: junit
          test_format: junit
          test_path: target/surefire-reports/**
          coverage_format: jacoco/xml
          coverage_path: |
            target/site/jacoco/*.xml
            coverage_demo/site/jacoco/*.xml
          cli_version: 213.3.16
